# Generated by Django 4.2.5 on 2023-10-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alumno_has_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuarios', models.IntegerField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('usuario', models.CharField(db_column='Usuario', max_length=100)),
                ('contraseña', models.CharField(db_column='Contraseña', max_length=100)),
                ('correo', models.CharField(db_column='Correo', max_length=100)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.RemoveField(
            model_name='alumno_has_genero',
            name='fk_Alumno',
        ),
        migrations.RemoveField(
            model_name='alumno_has_genero',
            name='fk_Genero',
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Alumno_has_Genero',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
