# Generated by Django 4.2.5 on 2023-10-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usuario_remove_alumno_has_genero_fk_alumno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idUsuarios',
            field=models.IntegerField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
