# Generated by Django 4.2.5 on 2023-10-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_usuario_usuario_alter_usuario_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarios',
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='Usuarios',
        ),
    ]
