# Generated by Django 4.2.5 on 2023-10-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_usuario_usuarios_alter_usuarios_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='contraseña',
            field=models.CharField(db_column='contraseña', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='correo',
            field=models.CharField(db_column='correo', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='usuario',
            field=models.CharField(db_column='usuario', max_length=100),
        ),
    ]
