# Generated by Django 3.2.4 on 2023-10-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_usuarios_contraseña_alter_usuarios_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(db_column='correp', max_length=100)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('pregun1', models.CharField(db_column='pregun1', max_length=100)),
                ('pregun2', models.CharField(db_column='pregun2', max_length=100)),
                ('pregun3', models.CharField(db_column='pregun3', max_length=100)),
                ('pregun4', models.CharField(db_column='pregun4', max_length=100)),
                ('pregun5', models.CharField(db_column='pregun5', max_length=100)),
                ('pregun6', models.CharField(db_column='pregun6', max_length=100)),
                ('pregun7', models.CharField(db_column='pregun7', max_length=100)),
                ('pregun8', models.CharField(db_column='pregun8', max_length=100)),
                ('pregun9', models.CharField(db_column='pregun9', max_length=100)),
                ('pregun10', models.CharField(db_column='pregun10', max_length=100)),
            ],
            options={
                'db_table': 'respuesta',
            },
        ),
    ]
