# Generated by Django 3.2.4 on 2023-10-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_encuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='correo',
            field=models.CharField(db_column='correo', max_length=100),
        ),
        migrations.AlterModelTable(
            name='encuesta',
            table='formulario',
        ),
    ]
