# Generated by Django 3.2.4 on 2023-10-19 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20231019_1635'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='encuesta',
            table='formula',
        ),
    ]
