# Generated by Django 3.2.4 on 2023-12-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_encuesta_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='idUsuarios',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
